// Manually edited!
// https://github.com/cloudflare/workers-sdk/issues/5082
//
// Generated by Wrangler on Tue Feb 27 2024 15:54:54 GMT-0500 (Eastern Standard Time)
// by running `wrangler types`

interface Env {
  KV: KVNamespace;
  ENVIRONMENT: "development" | "preview" | "production";
  SESSION_SECRET: string;
  TOTP_SECRET: string;
  RESEND_API_KEY: string;
  D1: D1Database;
}
