// Generated by Wrangler on Sun Mar 17 2024 10:09:36 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	ENVIRONMENT: string;
	SESSION_SECRET: string;
	TOTP_SECRET: string;
	RESEND_API_KEY: string;
	D1: D1Database;
}
