# https://developers.cloudflare.com/workers/configuration/compatibility-dates/
compatibility_date = "2024-02-03"
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
  { id = "ratce-kv-dev", binding="KV" }
]

# https://developers.cloudflare.com/d1/learning/local-development/#develop-locally-with-pages
[[ d1_databases ]]
binding = "D1"
database_name = "ratce-d1-dev"
database_id = "intentionally-dummy-id"
preview_database_id = "D1"
migrations_table = "d1_migrations"
migrations_dir = "drizzle"

[[ env.preview.d1_databases ]]
binding = "D1"
database_name = "ratce-d1-preview"
database_id = "1af6c629-8202-42e9-9982-e7f5ecc53f98" # pnpm wrangler d1 info ratce-d1-preview
preview_database_id = "D1"
migrations_table = "d1_migrations"
migrations_dir = "drizzle"

[[ env.prod.d1_databases ]]
binding = "D1"
database_name = "ratce-d1-prod"
database_id = "1837ece5-979f-485b-9892-1d25aec2f6d9" # pnpm wrangler d1 info ratce-d1-prod
preview_database_id = "D1"
migrations_table = "d1_migrations"
migrations_dir = "drizzle"


