# https://developers.cloudflare.com/workers/configuration/compatibility-dates/
compatibility_date = "2023-12-01"

# https://developers.cloudflare.com/d1/learning/local-development/#develop-locally-with-pages
[[ d1_databases ]]
binding = "DB"
database_name = "ratce-db-dev"
database_id = "intentionally-dummy-id"
preview_database_id = "DB"
migrations_table = "d1_migrations"
migrations_dir = "drizzle"

[[ env.prod.d1_databases ]]
binding = "DB"
database_name = "ratce-db-prod"
database_id = "0f77f73b-b9c3-4850-b6e2-9ab80c1b56c0" # pnpm wrangler d1 info ratce-db-prod
preview_database_id = "DB"
migrations_table = "d1_migrations"
migrations_dir = "drizzle"

[[ env.preview.d1_databases ]]
binding = "DB"
database_name = "ratce-db-preview"
database_id = "05ff0b5a-7459-4be2-a304-024a60ac34db" # pnpm wrangler d1 info ratce-db-preview
preview_database_id = "DB"
migrations_table = "d1_migrations"
migrations_dir = "drizzle"
