# https://developers.cloudflare.com/workers/configuration/compatibility-dates/
compatibility_date = "2024-02-03"

# https://developers.cloudflare.com/workers/runtime-apis/nodejs/#enable-nodejs-with-workers
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
  { id = "local-kv-dev", binding="KV" }
]

# https://developers.cloudflare.com/d1/learning/local-development/#develop-locally-with-pages
[[ d1_databases ]]
binding = "D1"
database_name = "local-d1-dev"
database_id = "intentionally-dummy-id-leave-as-is"
preview_database_id = "D1"
migrations_table = "d1_migrations"
migrations_dir = "drizzle"

[[ env.preview.d1_databases ]]
binding = "D1"
database_name = "ratce-d1-preview"
# pnpm wrangler d1 create ratce-d1-preview
# pnpm wrangler d1 info ratce-d1-preview
database_id = "f954307f-89e9-447c-85c1-e46e9f905db4" 
preview_database_id = "D1"
migrations_table = "d1_migrations"
migrations_dir = "drizzle"

[[ env.prod.d1_databases ]]
binding = "D1"
database_name = "ratce-d1-prod"
# pnpm wrangler d1 create ratce-d1-prod
# pnpm wrangler d1 info ratce-d1-prod
database_id = "2377e1c8-f900-4295-b666-81dcfb2caea8"
preview_database_id = "D1"
migrations_table = "d1_migrations"
migrations_dir = "drizzle"

