# https://developers.cloudflare.com/workers/configuration/compatibility-dates/
compatibility_date = "2023-12-01"

# https://developers.cloudflare.com/d1/learning/local-development/#develop-locally-with-pages
[[ d1_databases ]]
binding = "DB"
database_name = "ratce-db"
database_id = "af427c2e-6c4e-4791-a747-cf4840e97b99" # pnpm wrangler d1 info ratce-db
preview_database_id = "DB"
migrations_table = "d1_migrations"
migrations_dir = "drizzle"

# pnpm wrangler d1 info ratce-db -c wrangler-prod.toml
# pnpm wrangler d1 info ratce-db-preview -c wrangler-prod.toml
# pnpm wrangler d1 migrations list ratce-db -c wrangler-prod.toml