# https://developers.cloudflare.com/workers/configuration/compatibility-dates/
compatibility_date = "2023-12-01"

# https://developers.cloudflare.com/d1/learning/local-development/#develop-locally-with-pages
[[ d1_databases ]]
binding = "DB"
database_name = "ratce-db-preview"
database_id = "05ff0b5a-7459-4be2-a304-024a60ac34db" # pnpm wrangler d1 info ratce-db-preview
preview_database_id = "DB"
migrations_table = "d1_migrations"
migrations_dir = "drizzle"

# pnpm wrangler d1 info ratce-db-preview
# pnpm wrangler d1 info ratce-db-preview -c wrangler-preview.toml
# pnpm wrangler d1 migrations list ratce-db-preview -c wrangler-preview.toml
# pnpm wrangler d1 execute ratce-db-preview --command "select * from d1_migrations;" -c wrangler-preview.toml